#!/usr/bin/env python3
"""
CSV to Markdown Converter for Chat Logs
Converts chat conversation CSV files into formatted Markdown documents.
"""

import csv
import os
from datetime import datetime


def csv_to_markdown(csv_file_path='chat.csv', output_file='chat_conversation.md'):
    """
    Convert a CSV chat log to a Markdown file.

    Args:
        csv_file_path: Path to the input CSV file
        output_file: Path to the output Markdown file

    Expected CSV format:
        timestamp, username, message
    """

    if not os.path.exists(csv_file_path):
        print(f"Error: CSV file '{csv_file_path}' not found!")
        return False

    try:
        # Read CSV data
        messages = []
        with open(csv_file_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                messages.append(row)

        if not messages:
            print("Warning: No messages found in CSV file!")
            return False

        # Generate Markdown
        markdown_content = generate_markdown(messages)

        # Write to file
        with open(output_file, 'w', encoding='utf-8') as mdfile:
            mdfile.write(markdown_content)

        print(f"✓ Successfully converted {len(messages)} messages to Markdown!")
        print(f"✓ Output file: {output_file}")
        return True

    except Exception as e:
        print(f"Error during conversion: {e}")
        return False


def generate_markdown(messages):
    """Generate Markdown content from messages."""

    # Header
    markdown = """# 💬 Chat Conversation

> Converted from CSV format

---

"""

    # Group messages by date if timestamp is available
    current_date = None

    for msg in messages:
        timestamp = msg.get('timestamp', '')
        username = msg.get('username', 'Unknown')
        message = msg.get('message', '')

        # Try to extract date from timestamp
        try:
            if timestamp:
                dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                date_str = dt.strftime('%Y-%m-%d')

                if date_str != current_date:
                    current_date = date_str
                    markdown += f"\n## 📅 {date_str}\n\n"

                time_str = dt.strftime('%H:%M:%S')
                timestamp_display = time_str
            else:
                timestamp_display = timestamp
        except:
            timestamp_display = timestamp

        # Add message
        markdown += f"### **{username}** `{timestamp_display}`\n\n"
        markdown += f"{message}\n\n"
        markdown += "---\n\n"

    # Footer with statistics
    markdown += f"""
## 📊 Statistics

- **Total Messages**: {len(messages)}
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

*Generated by ChatConvert-Toolkit*
"""

    return markdown


if __name__ == "__main__":
    print("=" * 50)
    print("CSV to Markdown Converter")
    print("=" * 50)

    # Look for CSV files in current directory
    csv_files = [f for f in os.listdir('.') if f.endswith('.csv')]

    if csv_files:
        print(f"\nFound CSV files: {', '.join(csv_files)}")
        csv_file = csv_files[0] if 'chat.csv' not in csv_files else 'chat.csv'
    else:
        csv_file = 'chat.csv'

    print(f"Using: {csv_file}\n")

    csv_to_markdown(csv_file)
