"""
Markdown Converter - Create GitHub-flavored Markdown from conversations.

Features:
- Date grouping
- Participant statistics
- GitHub-flavored markdown
- Code block formatting
- Emoji support
"""

import time
from datetime import datetime
from pathlib import Path

from .base_converter import BaseConverter
from ..models import Conversation, ConversionResult


class MarkdownConverter(BaseConverter):
    """Convert conversations to Markdown format."""

    def get_file_extension(self) -> str:
        return 'md'

    def convert(self, conversation: Conversation, output_file: str) -> ConversionResult:
        """
        Convert conversation to Markdown.

        Config options:
        - group_by_date: Group messages by date (default: True)
        - include_stats: Include statistics footer (default: True)
        - style: 'compact' or 'detailed' (default: 'detailed')

        Args:
            conversation: Conversation to convert
            output_file: Path to output .md file

        Returns:
            ConversionResult
        """
        start_time = time.time()
        path = self._validate_output_path(output_file)

        try:
            # Get config
            group_by_date = self.config.get('group_by_date', True)
            include_stats = self.config.get('include_stats', True)
            style = self.config.get('style', 'detailed')

            # Generate Markdown
            markdown_content = self._generate_markdown(
                conversation,
                group_by_date=group_by_date,
                include_stats=include_stats,
                style=style
            )

            # Write to file
            self._write_file(path, markdown_content)

            processing_time = time.time() - start_time

            return self._create_result(
                success=True,
                output_file=str(path),
                message_count=len(conversation.messages),
                processing_time=processing_time,
                statistics={
                    'style': style,
                    'participants': len(conversation.get_participants_list()),
                }
            )

        except Exception as e:
            self.logger.error(f"Markdown conversion failed: {e}")
            return self._create_result(
                success=False,
                errors=[str(e)],
                processing_time=time.time() - start_time
            )

    def _generate_markdown(
        self,
        conversation: Conversation,
        group_by_date: bool = True,
        include_stats: bool = True,
        style: str = 'detailed'
    ) -> str:
        """Generate complete Markdown document."""

        # Header
        markdown = f"# 💬 {conversation.title}\n\n"
        markdown += f"> **Platform**: {conversation.platform}\n"

        date_range = conversation.get_date_range()
        if date_range[0]:
            start = date_range[0].strftime('%Y-%m-%d')
            end = date_range[1].strftime('%Y-%m-%d')
            if start == end:
                markdown += f"> **Date**: {start}\n"
            else:
                markdown += f"> **Period**: {start} to {end}\n"

        markdown += "\n---\n\n"

        # Messages
        if group_by_date and style == 'detailed':
            markdown += self._format_messages_by_date(conversation.messages)
        elif style == 'compact':
            markdown += self._format_messages_compact(conversation.messages)
        else:
            markdown += self._format_messages_detailed(conversation.messages)

        # Statistics
        if include_stats:
            markdown += self._generate_statistics(conversation)

        # Footer
        markdown += f"\n---\n\n*Generated by ChatConvert-Toolkit on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n"

        return markdown

    def _format_messages_by_date(self, messages: list) -> str:
        """Format messages grouped by date."""
        markdown = ""
        current_date = None

        for msg in messages:
            date_str = msg.timestamp.strftime('%Y-%m-%d')

            # Add date header if changed
            if date_str != current_date:
                current_date = date_str
                markdown += f"\n## 📅 {date_str}\n\n"

            time_str = msg.timestamp.strftime('%H:%M:%S')
            markdown += f"### **{msg.sender}** `{time_str}`\n\n"
            markdown += f"{msg.content}\n\n"
            markdown += "---\n\n"

        return markdown

    def _format_messages_detailed(self, messages: list) -> str:
        """Format messages with full timestamps."""
        markdown = ""

        for msg in messages:
            timestamp = msg.timestamp.strftime('%Y-%m-%d %H:%M:%S')
            markdown += f"### **{msg.sender}** `{timestamp}`\n\n"
            markdown += f"{msg.content}\n\n"
            markdown += "---\n\n"

        return markdown

    def _format_messages_compact(self, messages: list) -> str:
        """Format messages in compact style."""
        markdown = ""

        for msg in messages:
            timestamp = msg.timestamp.strftime('%Y-%m-%d %H:%M')
            markdown += f"**{msg.sender}** ({timestamp}): {msg.content}\n\n"

        return markdown

    def _generate_statistics(self, conversation: Conversation) -> str:
        """Generate statistics section."""
        participants = conversation.get_participants_list()

        # Calculate per-participant stats
        participant_stats = []
        for p in participants:
            count = sum(1 for m in conversation.messages if m.sender == p)
            participant_stats.append((p, count))

        # Sort by message count
        participant_stats.sort(key=lambda x: x[1], reverse=True)

        markdown = "\n## 📊 Conversation Statistics\n\n"
        markdown += f"- **Total Messages**: {len(conversation.messages)}\n"
        markdown += f"- **Participants**: {len(participants)}\n"

        # Participant breakdown
        markdown += "\n### Participant Activity\n\n"
        markdown += "| Participant | Messages | Percentage |\n"
        markdown += "|-------------|----------|------------|\n"

        total = len(conversation.messages)
        for username, count in participant_stats:
            percentage = (count / total * 100) if total > 0 else 0
            markdown += f"| {username} | {count} | {percentage:.1f}% |\n"

        return markdown
